version: v1.0
name: PixelExperience Continuous Integration
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: Wiki Validator and builder.
    task:
      jobs:
      - name: Job
        commands:
          - checkout
          - docker build --no-cache -t wiki_ci:latest .
          - docker run -e RUBYOPT='-W0' -e RSYNC_USERNAME=${RSYNC_USERNAME} -e RSYNC_PASSWORD=${RSYNC_PASSWORD} -e TELEGRAM_TOKEN=${TELEGRAM_TOKEN} -e SEMAPHORE_JOB_ID=${SEMAPHORE_JOB_ID} -e GH_PERSONAL_TOKEN=${GH_PERSONAL_TOKEN} -e SEMAPHORE_GIT_PR_NUMBER=${SEMAPHORE_GIT_PR_NUMBER} -e SEMAPHORE_ORGANIZATION_URL=${SEMAPHORE_ORGANIZATION_URL} wiki_ci:latest
      secrets:
        - name: Pixel-CI
